name: washio
description: "A Simple washing machine booking app."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter

  # Essential packages
  http: ^1.2.2
  intl: ^0.19.0
  supabase_flutter: ^2.6.0
  

  # Icons and images packages
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  image_path: "assets/icons/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/HomeIcon.svg
    - assets/images/main-icon.png

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
        - asset: fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: fonts/JetBrainsMono-Italic.ttf
          style: italic
